name: verossa
description: Verossa E-commerce demo


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  cloud_functions: ^0.7.0+1
  webview_flutter: ^1.0.7
  http_auth: ^0.3.1
  flutter_svg: ^0.19.1
  modal_progress_hud: ^0.1.3
  stripe_payment: ^1.0.8
  url_launcher: ^5.7.2
  flutter:
    sdk: flutter
  share: any


  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  carousel_pro: ^1.0.0
  material_design_icons_flutter: 4.0.5345
  http: ^0.12.2
  badges: ^1.1.1
  photo_view: ^0.10.2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  shared_preferences: ^0.5.10
  dart_notification_center: ^1.0.0+1
  provider: ^4.3.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Cormorant
      fonts:
        - asset: fonts/Cormorant-Medium.ttf
  assets:
    - images/IMG_1394.jpg
    - images/IMG_1368.jpg
    - images/Verossa-Reiger.jpg
    - images/Verossa-Cameraman.jpg
    - images/Verossa-Tree.jpg
    - images/VerossaSmallLogo.jpg
    - images/Verossa-SunTree.jpg
    - images/Verossa-SunTreeBW.jpg
    - images/Verossa-SunTreeCL.jpg
    - images/Verossa-Fall.jpg
    - images/Verossa-FallBW.jpg
    - images/Verossa-FallCL.jpg
    - images/Verossa-Heli.jpg
    - images/Verossa-HeliBW.jpg
    - images/Verossa-HeliCL.jpg
    - images/Verossa-Field.jpg
    - images/Verossa-FieldBW.jpg
    - images/Verossa-FieldCL.jpg
    - images/Verossa-Thunder.jpg
    - images/Verossa-ThunderBW.jpg
    - images/Verossa-ThunderCL.jpg
    - images/Verossa-Scotland.jpg
    - images/Verossa-ScotlandBW.jpg
    - images/Verossa-ScotlandCL.jpg
    - images/Verossa-CheckoutLogo.png
    - images/Apple_Pay_Mark_RGB_041619.svg
    - images/Google_Pay-Logo.wine.svg
    - images/PayPal.svg





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
